[package]
name = "tod8"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
borsh = { version = "1.5.5", features = ["derive"] }
solana-program = "2.2.1"

[lib]
crate-type = ["cdylib"]
